In [1]:
#Use this space to test xarray behaviors
import xarray 

data = xarray.DataArray([1,2,3,4])

def add_one(datum):
    result = datum + 1
    print(result)
    return result 


print(xarray.where(data < 3, 1, add_one(data)))

<xarray.DataArray (dim_0: 4)>
array([2, 3, 4, 5])
Dimensions without coordinates: dim_0
<xarray.DataArray (dim_0: 4)>
array([1, 1, 4, 5])
Dimensions without coordinates: dim_0


Here, the return argument is a scalar. It is only called once, and this value is taken to fill the array. 

In [3]:
def return_one(): 
    print('here!')
    return 1 

print(xarray.where(data < 2, 2, return_one()))

here!
<xarray.DataArray (dim_0: 4)>
array([2, 1, 1, 1])
Dimensions without coordinates: dim_0


In [4]:
xarray.Dataset(data_vars=dict(first=()))

IndexError: tuple index out of range

In [5]:
 
left = [True, False, False, False] 
right = [return_one(), return_one(), return_one(), return_one()]

print(left and right)



here!
here!
here!
here!
[1, 1, 1, 1]


2D boolean indexing is not a thing. 

In [3]:
import numpy as np

mask = xarray.DataArray([[True, False],[True,False]])
data = xarray.DataArray([[1,2],[3,4]],dims = {'row': ['a','b'],'col': [1,2]})
delta = xarray.DataArray([[1,1],[1,1]],dims = {'row': ['a','b'],'col': [1,2]})
beta = xarray.DataArray([[9,9],[9,9]])
#print(np.add(data,delta, where = mask))

threeD = np.dstack((data,delta,beta))

In [4]:
mask = threeD > 2
threeD[mask]

array([9, 9, 3, 9, 4, 9])